language: python

python: '2.7'
sudo: false

install:
  - pip install pytest

script:
  - py.test

before_deploy:
   - make

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: calculator
  handler_name: lambda_function.lambda_handler
  region: eu-central-1
  runtime: python2.7
  publish: true
  zip: dist/lambda.zip
  role: $ROLE

notifications:
    email: false
